version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./config
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - production-network
    depends_on:
      - "faceframe1"
      - "faceframe2"

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: faceframe
      #PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - production-network
    restart: unless-stopped

  faceframe1:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: faceframe1
    ports:
      - "3000"
    networks:
      - production-network

  faceframe2:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: faceframe2
    ports:
      - "3000"
    networks:
      - production-network

networks:
  production-network:
    driver: bridge
